export const songs = [
  {
    color: "#3498db",
    title: "Soulful Serenade",
    author: "Various Artists",
    liked: true,
    length: "1:45:32",
  },
  {
    color: "#e74c3c",
    title: "Smooth Operator",
    author: "Sade",
    album: "Diamond Life",
    liked: false,
    length: "4:59",
    explicit: false,
  },
  {
    color: "#2ecc71",
    title: "Ain't No Mountain High Enough",
    author: "Marvin Gaye, Tammi Terrell",
    liked: true,
    length: "2:29",
  },
  {
    color: "#9b59b6",
    title: "Lovely Day",
    author: "Bill Withers",
    liked: true,
    length: "4:15",
  },
  {
    color: "#f39c12",
    title: "Golden",
    author: "Jill Scott",
    album: "Beautifully Human: Words and Sounds Vol. 2",
    liked: false,
    length: "3:52",
    explicit: false,
  },
  {
    color: "#34495e",
    title: "What's Going On",
    author: "Marvin Gaye",
    liked: true,
    length: "3:53",
  },
  {
    color: "#d35400",
    title: "Summertime",
    author: "Ella Fitzgerald, Louis Armstrong",
    liked: false,
    length: "4:59",
    explicit: false,
  },
  {
    color: "#c0392b",
    title: "I Can't Help It",
    author: "Michael Jackson",
    album: "Off the Wall",
    liked: true,
    length: "4:29",
    explicit: false,
  },
  {
    color: "#16a085",
    title: "At Last",
    author: "Etta James",
    liked: false,
    length: "3:02",
  },
  {
    color: "#27ae60",
    title: "Lovely Night",
    author: "John Legend",
    liked: true,
    length: "3:34",
    explicit: false,
  },
  {
    color: "#8e44ad",
    title: "Feeling Good",
    author: "Nina Simone",
    liked: false,
    length: "2:54",
  },
];
