import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Providers } from "@/redux/provider";
import { NavContextProvider } from "./_context/nav-context";
import "./globals.css";
import TopNav from "./_navigation/top-nav/top-nav";
import LeftNav from "./_navigation/left-nav/left-nav";
import MusicPlayer from "./_navigation/music-player/music-player";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <NavContextProvider>
              <TopNav />
              <div className="flex w-screen max-h-screen flex-col items-center px-4">
                <div className="flex flex-row w-full h-full">
                  <LeftNav />
                  {children}
                </div>
                <MusicPlayer />
              </div>
            </NavContextProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
